language: python
python:
  - "2.7"
# Django environment
environment:
  - DJANGO_VERSION=1.9
# command to install dependencies
install: "pip install -r requirements.txt"
# start required services
services:
  - mysql
# command to run tests
script: python manage.py test --settings=IdeasHubProject.settings.travis_ci_settings